[package]
name = "rust_audio_resampler"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_audio_resampler"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }
numpy = "0.21.0"
ndarray = "0.15.4"
rubato = "0.14.1"